<a href="https://colab.research.google.com/github/wincmoriya/pytorch-handson/blob/main/%E8%87%AA%E5%8B%95%E5%BE%AE%E5%88%86.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 自動微分
あまり使う機会は無いが誤差逆伝播の計算をするときに、この自動微分がバックで働いているという認識を持っておく。

In [1]:
import torch

$y = 3 x^{3}$

In [2]:
# yのxに対する勾配を自動微分で求める
# 何かしらの値を入れておかなきゃいけないので2を入れておく
# requires_grad=True→勾配計算が必要かどうか
x = torch.tensor([2], dtype=torch.float32, requires_grad=True)

In [3]:
y = 3 * x ** 3

In [4]:
# backwardして欲しい変数に対して勾配を求める
y.backward()

In [5]:
x.grad

tensor([36.])

In [6]:
# 試しに2つの変数がある場合
x1 = torch.tensor([4], dtype=torch.float32, requires_grad=True)
x2 = torch.tensor([2], dtype=torch.float32, requires_grad=True)

In [7]:
y = 2 * x1 ** 2 + 3 * x2 ** 3

In [8]:
y.backward()

In [9]:
x1.grad

tensor([16.])

In [10]:
x2.grad

tensor([36.])